namespace: "qsypoq"

name: "vmware_desktop"

version: "0.1.0"

readme: "README.md"

authors:
- "Adam Qsypoq Magnier <adam@magnier.io> (https://www.magnier.io)"

description: Modules interacting with VMware's desktop REST API. (Workstation/Fusion Pro)

license_file: "LICENSE"

tags:
- vmware
- workstation
- fusion
- api
- windows
- linux
- mac

dependencies: {}

repository: "https://github.com/qsypoq/Ansible-VMware-Workstation-Fusion-Pro-Modules"

documentation: "https://github.com/qsypoq/Ansible-VMware-Workstation-Fusion-Pro-Modules"

homepage: "https://github.com/qsypoq/Ansible-VMware-Workstation-Fusion-Pro-Modules"

issues: "https://github.com/qsypoq/Ansible-VMware-Workstation-Fusion-Pro-Modules/issues"